const BOT_STATUS = {
	HOME_PAGE : 1,
	ASKING_BOOKING_ARRIVAL : 2,
	ASKING_BOOKING_DIPARTURE : 3,
	ASKING_BOOKING_DATE : 4,
	SHOWING_AVAILABLE_FLIGHTS : 5,
	THANKS_FOR_BOOKING : 6,

	SHOWING_LIST_FOR_FLIGHT_STATUS : 7,
	TALK_TO_AGENT: 8,

      }

export default {
	BOT_STATUS,
};